### PR TITLE
Issue 10 send message endpoint

### PR DESCRIPTION
**Pull request by devansh2001**

### CODE REVIEW

**Comment by devansh2001** [comment]
Steps to review this PR:
1. Start the front end and back end
2. When you go to l`ocalhost:3000`, you will either see `dponda` or `vtrivedi` on the top left. Let's assume you see `vtrivedi`. Now, in a second tab/window open `localhost:3000` again. If you see `dponda` then great. If you see `vtrivedi` again, then close both windows and then repeat step 2 till you have dponda on one tab and vtrivedi on another (the username will later be derived from the login screen but right now I have it such that there is a 50-50 chance of getting `dponda` and `vtrivedi`
3. Go to the tab where the username on the top-left is `dponda`.
4. Now click on the contact card of `vtrivedi`.
5. Type your message and hit send
6. Now go to the tab where the top left says `vtrivedi`
7. Open the console
8. There should be a JSON in the console logs where your message appears.

You can repeat steps 3 - 8 starting from the tab where the username is `vtrivedi` and see the message appear on the console of the tab where the username is `dponda`.

**Comment by PRERNARAVI** [comment]
All steps work perfectly!
One small thing I noticed is that for a message from dponda to trivedi the JSON is being printed multiple times to the console even though I selected it only once. This does not happen for the reversed scenario. Was this intentional or does it have anything to do with the way the JSON was created?

**Comment by devansh2001** [comment]
Yeah I have no idea why that's happening. It's weird. But I'm assuming it just has to do with the fact that JS is async, so order of execution of lines is not deterministic in some cases. If it does show up on the current chats as multiple messages, we will add a unique ID to each messages and add to the messages list only if that message ID hasn't been seen before

**Comment by PRERNARAVI** [comment]
Okay the message ID sounds like a good idea. If we decide to implement additional features like replying to a specific message or forwarding a message, the ID could come in handy. 
Otherwise, this PR is perfect so you can go ahead with the merge!

**Pull request merged**
